name: Print logs
inputs:
  files:
    description: Files to print.
    required: true
  working-directory:
    description: Working directory.
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
  - name: Print files
    env:
      files: ${{ inputs.files }}
    shell: bash
    run: |
      set +e
      pushd '${{ inputs.working-directory }}' &> /dev/null

      for file in $files; do
        if [ -f "$file" ]; then
          echo -e ::group::File: $file
          cat $file
          echo ::endgroup::
        fi
      done

      popd &> /dev/null
      exit 0
